<?php

/**
 * Comp315 2011
 */

require_once("Species.inc");
require_once("Specimen.inc");
require_once("Class.inc");
require_once("Collection.inc");
require_once("CollectionNote.inc");
require_once("DetHistory.inc");
require_once("Family.inc");
require_once("Genus.inc");
require_once("Group.inc");
require_once("Kingdom.inc");
require_once("Loans.inc");
require_once("LoansNote.inc");
require_once("Locality.inc");
require_once("LocalityNote.inc");
require_once("Order.inc");
require_once("Personnel.inc");
require_once("Phylum.inc");
require_once("Project.inc");
require_once("Reference.inc");
require_once("ReferenceLinks.inc");
require_once("SpeciesNotes.inc");
require_once("SpecimenNotes.inc");
require_once("ImageArchive.inc");

require_once("Table.inc");
require_once("WebUsers.inc");

?>